# Site settings
title: Dynamical Systems and AI Research Group
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, leave empty for user/organization sites
url: "https://vigsnar.github.io" # the base hostname for your GitHub Pages site

linkedin_username: vignar
researchgate_username: Vignesh-Narayanan
googlescholar_url: rirGB10AAAAJ

# Build settings
markdown: kramdown
